### ISSUE TITLE
PP Calculation

### ISSUE THREAD

**Issue by tsunyoku** [spookybear0/spookybot#2]
To ensure your not is mostly accurate, I wouldn’t recommend using ripple’s api for pp calculation as it is far from bancho’s. If you are running the bot on a vps, I suggest you compile the PerformanceCalculator bancho uses (available on peppy’s github) and using that to calculate maps remotely as it will give you accurate results.

**Comment by tsunyoku** [comment]
Also I generally suggest you read into async and making as much of your code async’d as possible as it will make your speeds much better and efficient for people who use your bot, it’d definitely make it much faster than Tillerino for example.

Edit: Reading through the code more I notice some is async’d, but definitely async every web request you do (the pp one so not) as they are normally what will benefit from async the most

**Comment by spookybear0** [comment]
I am planning on making web requests async and I just realized that they are not. PP calculation is at most 1pp away from Tillerino and other pp calculators so I don't think it is a problem, but using the api does make it slower.

**Comment by spookybear0** [comment]
I am also planning on adding a better pp system in the future to cut down on internet and increase speed.

**Comment by spookybear0** [comment]
@mbruhyo Instead of the PerformanceCalculator you were talking about, I think I am going to use pyoppai.
